// In order to use the MultipleSelect with custom value
// you need to define the constant with {title: xxxx} structure

export const COUNTRY_LIST = [
  'Adjuntas',
  'Aguada',
  'Aguadilla',
  'Aguas Buenas',
  'Aibonito',
  'Arecibo',
  'Arroyo',
  'Añasco',
  'Barceloneta',
  'Barranquitas',
  'Bayamón',
  'Cabo Rojo',
  'Caguas',
  'Camuy',
  'Canóvanas',
  'Carolina',
  'Cataño',
  'Cayey',
  'Ceiba',
  'Ciales',
  'Cidra',
  'Coamo',
  'Comerío',
  'Corozal',
  'Culebra',
  'Dorado',
  'Fajardo',
  'Florida',
  'Guayama',
  'Guayanilla',
  'Guaynabo',
  'Gurabo',
  'Guánica',
  'Hatillo',
  'Hormigueros',
  'Humacao',
  'Isabela',
  'Jayuya',
  'Juana Díaz',
  'Juncos',
  'Lajas',
  'Lares',
  'Las Marías',
  'Las Piedras',
  'Loiza',
  'Luquillo',
  'Manatí',
  'Maricao',
  'Maunabo',
  'Mayagüez',
  'Moca',
  'Morovis',
  'Naguabo',
  'Naranjito',
  'Orocovis',
  'Patillas',
  'Peñuelas',
  'Ponce',
  'Quebradillas',
  'Rincón',
  'Rio Grande',
  'Sabana Grande',
  'Salinas',
  'San Germán',
  'San Juan',
  'San Lorenzo',
  'San Sebastián',
  'Santa Isabel',
  'Toa Alta',
  'Toa Baja',
  'Trujillo Alto',
  'Utuado',
  'Vega Alta',
  'Vega Baja',
  'Vieques',
  'Villalba',
  'Yabucoa',
  'Yauco',
];

export const GENDER_LIST = [
  { title: 'Masculino' },
  { title: 'Femenino' },
  { title: 'No Binarie' },
  { title: 'Agénero' },
  { title: 'Prefiero No Decir' },
];

export const AREA_OF_FOCUS = [
  { title: 'Asuntos de la Mujer' },
  { title: 'Uso Problemático de Sustancias' },
  { title: 'Asuntos de la Comunidad LGBT+' },
  { title: 'Coraje' },
  { title: 'Problemas Alimenticios' },
  { title: 'Asuntos de Etnia' },
  { title: 'Ansiedad' },
  { title: 'Dificultades Emocionales' },
  { title: 'Asuntos de Raza' },
  { title: 'Trastorno Bipolar' },
  { title: 'Quemazón' },
  { title: 'Condición Médica Crónica' },
  { title: 'Cambio en Profesión o Carrera' },
  { title: 'Asuntos Relacionados a Hijxs' },
  { title: 'Codependencia' },
  { title: 'Diversidad Cognitiva o Intelectual' },
  { title: 'Problemas de Comunicación' },
  { title: 'Conflictos en Relación de Pareja' },
  { title: 'COVID 19' },
  { title: 'Pérdidas' },
  { title: 'Toma de Decisiones' },
  { title: 'Depresión' },
  { title: 'Diversidad Funcional' },
  { title: 'Discriminación' },
  { title: 'Aculturación' },
  { title: 'Violencia de Género' },
  { title: 'Problemas de Sueño' },
  { title: 'Problemas Familiares' },
  { title: 'Miedos y Fobias' },
  { title: 'Pobre Tolerancia a la Frustración' },
  { title: 'Asuntos de Identidad de Género' },
  { title: 'Culpa' },
  { title: 'Cambios de Humor' },
  { title: 'Celos' },
  { title: 'Problemas Laborales' },
  { title: 'Cambio en Estilo de Vida' },
  { title: 'Sobrepeso' },
  { title: 'Pensamientos Obsesivos' },
  { title: 'Comportamientos Compulsivos' },
  { title: 'Problemas de Dolor' },
  { title: 'Ataques de Pánico' },
  { title: 'Trastorno de Personalidad' },
  { title: 'Maternidad y Paternidad' },
  { title: 'Desmotivación' },
  { title: 'Enfermedad Psicosomática' },
  { title: 'Resentimiento' },
  { title: 'Conductas Autodestructivas' },
  { title: 'Pobre Autoestima' },
  { title: 'Abuso Sexual' },
  { title: 'Disfunciones Sexuales' },
  { title: 'Exclusión Social' },
  { title: 'Pobres Destrezas Sociales' },
  { title: 'Estrés' },
  { title: 'Conductas y Pensamientos Suicidas' },
  { title: 'Trauma' },
  { title: 'Violencia' },
  { title: 'Orientación Vocacional' },
  { title: 'Otro' }
];

export const HEALTH_PLANS = [
  { title: 'No soy proveedor de planes de salud' },
  { title: 'Triple S' },
  { title: 'MCS' },
  { title: 'Mapfre' },
  { title: 'FHC' },
  { title: 'Tricare' },
  { title: 'MMM' },
  { title: 'First Medical' },
  { title: 'Medicare' },
  { title: 'Humana' }
];

export const POPULATION_SERV = [
  { title: 'Adultos' },
  { title: 'Niños' },
  { title: 'Jóvenes Adultos' },
  { title: 'Adolescentes' },
  { title: 'Adultos Mayores' },
  { title: 'Familias o Parejas' }
];

export const THEORETICAL_APPROACHES = [
  { title: 'Cognitivo Conductual' },
  { title: 'Humanista' },
  { title: 'Integrativo' },
  { title: 'Sistemas de Familia' },
  { title: 'Psicoanalista' },
  { title: 'Psicodinámico' },
  { title: 'Terapia Dialéctica Conductual' },
  { title: 'Terapia de Aceptación y Compromiso' },
  { title: 'Neurofeedback' },
  { title: 'Biofeedback' },
  { title: 'Arte Terapia' },
  { title: 'Terapias Expresivas' },
  { title: 'Terapia de Música' },
  { title: 'Psicodrama' },
  { title: 'Terapia de Escritura' },
  { title: 'Terapia de Juego' }
];

// export const EXPERTISE = [
//   { title: 'Asuntos de la Mujer' },
//   { title: 'Asuntos de la Comunidad LGBT+' },
//   { title: 'Asuntos de Etnia' },
//   { title: 'Asuntos de Raza' },
// ];

export const LANGUAGES = [{ title: 'Español' }, { title: 'Inglés' }, { title: 'ASL' }, { title: 'PRSL' }];
